- hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - homebrew/cask
    homebrew_packages:
      - name: anyenv
      - name: git
      - name: go
      - name: gpg
      - name: mas
    homebrew_cask_packages:
      - name: app-cleaner
      - name: clipy
      - name: docker
      - name: deepl
      - name: google-cloud-sdk
      - name: google-drive
      - name: gitkraken
      - name: jetbrains-toolbox
      - name: karabiner-elements
      - name: rectangle
      - name: visual-studio-code
    apps:
      - { name: "Tailscale", id: "1475387142" }

  tasks:
    - name: setup homebrew
      ignore_errors: yes
      block:
        - name: homebrew update
          homebrew:
            update_homebrew: yes
        - name: homebrew tap
          homebrew_tap:
            name: '{{ item }}'
            state: present
          with_items: '{{ homebrew_taps }}'
        - name: homebrew packages install
          homebrew:
            name: '{{ item.name }}'
            state: '{{ item.state | default("present") }}'
          with_items: '{{ homebrew_packages }}'
    - name: homebrew cask packages install
      community.general.homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
    - name: install from AppStore
      block:
        - name: fetch list
          command: mas
          register: installed_list
          check_mode: no
          changed_when: no
        - name: install from AppStore
          command: "mas install {{ item.id }}"
          when: "installed_list.stdout_lines | select('search', item.id) | list | length == 0"
          loop: "{{ apps }}"
